apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: vote-staging
commonLabels:
  app: vote-staging
  env: staging
resources:
- ../base/
resources:
- deployment.yaml
- service.yaml

replicas:
  - name: vote
    count: 8

images:
  - name: schoolofdevops/vote
    newTag: v4
    #    newName: lfs269/vote
    #    digest : sha256:24a0c4b4a4c0eb97a1aabb8e29f18e917d05abfe1b7a7c07857230879ce7d3d3
   
namespace: instavote
