apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization
metadata:
  name: vote-staging
commonLabels:
  app: vote-staging
resources:
- ../base
labels:
- includeSelectors: true
  pairs:
    app: vote-staging
patches:
- path: deployment.yaml
- path: service.yaml
